services:
  - type: web
    name: eventvendor
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: EventVendor
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: false
        value: base64:HOdPFAJkrnvz1Aec4W9RH7jrhx2ofHOBG+bW8xF3G+E=
      - key: DB_CONNECTION
        value: mysql
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: FILESYSTEM_DISK
        value: local
      - key: MAIL_MAILER
        value: resend
      - key: MAIL_FROM_NAME
        value: EventVendor
